.lint:
  stage: lint
  rules:
    - !reference [.default_rules, rules]
  allow_failure: true
  before_script:
    - !reference [.setup, before_script]
  script:
    - |
      echo "ğŸ”§ Running dmt lint..."
      dmt lint ./
